
### GET Users
GET http://localhost:6600/api/users HTTP/2.0

### GET User by Id
GET http://localhost:6600/api/users/12 HTTP/2.0

### Post User
POST http://localhost:6600/api/users HTTP/2.0
content-type: application/json

{
    "email": "user@email.com",
    "password": "abcdefghijk"
}

### Login
POST http://localhost:6600/api/login HTTP/2.0
content-type: application/json

{
    "email": "user@email.com",
    "password": "abcdefghijk"
}
