[package]
name = "actix-logs"
version = "0.1.0"
authors = ["Joel Crosby <joelcrosby@live.co.uk>"]
edition = "2018"

[dependencies]
actix-web = "3.3.2"
diesel = { version = "1.4.5", features = ["postgres"] }
r2d2-diesel = "1.0.0"
dotenv = "0.15.0"
env_logger = "0.8.3"